name: Amazon Job Scanner

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scan-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager
          
      - name: Run job scanner
        run: python job_scanner.py
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: job-scan-results
          path: |
            jobs_found.txt
            job_scan.log
